version: '3.9'

services:
  turboasya:
    image: ghcr.io/siberianmh/turboasya:${TURBOASYA_VERSION:-0.3.6}
    ports:
      - '8080:8080'
    environment:
      MYSQL_DSN: '${MYSQL_USERNAME:-root}:${MYSQL_PASSWORD:-password}@tcp(database)/${MYSQL_DATABASE:-turboasya}'
      STORAGE: disk
      DISK_PATH: /mnt/data
    volumes:
      - turboasya_data:/mnt/data
    depends_on:
      database:
        condition: service_healthy

  database:
    image: 'mysql:8'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password} # The MySQL root password
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password} # The MySQL password
      MYSQL_DATABASE: ${MYSQL_DATABASE:-turboasya} # The MySQL default database
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 10s
      retries: 10
    volumes:
      - turboasya_mysql_data:/var/lib/mysql

volumes:
  turboasya_mysql_data:
  turboasya_data:
